services:
  stac-browser:
    image: ghcr.io/geowerkstatt/stac-browser:latest
    ports:
      - 8080:8080
    environment:
      SB_catalogUrl: "https://localhost:5173/api/stac"
      SB_locale: "de-CH"
      SB_fallbackLocale: "de-CH"
      SB_supportedLocales: "de-CH"

  db:
    image: postgis/postgis
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: HAPPYWALK
      POSTGRES_PASSWORD: SOMBERSPORK
      POSTGRES_DB: geopilot
    healthcheck:
      test: "pg_isready -U HAPPYWALK -d geopilot -h db"
      interval: 3s
      timeout: 1s
      retries: 20
      start_period: 25s

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 3001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: BOUNCEAUTO
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./config/pgadmin4-servers.json:/pgadmin4/servers.json
    entrypoint:
      - /bin/sh
      - -c
      - |
        /bin/echo '*:*:geopilot:HAPPYWALK:SOMBERSPORK' > /tmp/.pgpass
        chmod 0600 /tmp/.pgpass
        /entrypoint.sh
    depends_on:
      db:
        condition: service_healthy

  interlis-check-service:
    image: ghcr.io/geowerkstatt/interlis-check-service:latest
    restart: unless-stopped
    ports:
      - 3080:80

  geopilot:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 5173:80
    environment:
      ConnectionStrings__Context: Server=db;Port=5432;Database=geopilot;User Id=HAPPYWALK;Password=SOMBERSPORK;
      ReverseProxy__Clusters__stacBrowserCluster__Destinations__stacBrowserDestination__Address: http://stac-browser:8080/
      Auth__Authority: https://login.microsoftonline.com/16e916d3-12c9-4353-ad04-5a4319422e03/v2.0
      Auth__ClientId: ac09549e-6cf8-40fe-91a9-25515ec71954
      Validation__InterlisCheckServiceUrl: http://interlis-check-service/
    volumes:
      - ./src/Geopilot.Api/Uploads:/uploads
      - ./src/Geopilot.Api/Persistent:/assets
      - ./README.md:/public/info-hilfe.md
      - ./LICENSE:/public/nutzungsbestimmungen.md
    depends_on:
      db:
        condition: service_healthy
