using Geopilot.PipelineCore.Pipeline;

namespace Geopilot.Pipeline;

/// <inheritdoc />
internal class PipelineFileManager : IPipelineFileManager
{
    private readonly string basePath;

    /// <summary>
    /// Create a PipelineFileManager with the specified base path for storing temporary files. The base path is used as the root directory for all temporary files generated by the pipeline.
    /// </summary>
    /// <param name="basePath">The base path for storing temporary files.</param>
    /// <param name="stepDirectory">The directory for the specific pipeline step.</param>
    public PipelineFileManager(string basePath, string stepDirectory)
    {
        if (!string.IsNullOrEmpty(stepDirectory))
            this.basePath = Path.Combine(basePath, stepDirectory);
        else
            this.basePath = basePath;

        if (!Path.Exists(this.basePath))
            Directory.CreateDirectory(this.basePath);
    }

    /// <inheritdoc />
    public IPipelineFile GeneratePipelineFile(string originalFileName, string fileExtension)
        => GeneratePipelineFile(string.Empty, originalFileName, fileExtension);

    /// <inheritdoc />
    public IPipelineFile GeneratePipelineFile(string originalRelativePath, string originalFileName, string fileExtension)
    {
        ArgumentNullException.ThrowIfNull(originalRelativePath);

        // OriginalRelativePath is metadata only — every generated file lives flat under basePath
        // with a GUID-disambiguated name, regardless of its logical directory. The
        // normalization here enforces the canonical-form contract of
        // IPipelineFile.OriginalRelativePath (forward slashes, no '.' / '..' segments, no
        // rooted paths) so downstream consumers can rely on it.
        var normalized = NormalizeRelativePath(originalRelativePath);
        var filePath = Path.Combine(this.basePath, $"{originalFileName}_{Guid.NewGuid()}.{fileExtension}");
        return new PipelineFile(filePath, originalFileName + "." + fileExtension, normalized);
    }

    /// <inheritdoc />
    public async Task<IPipelineFile> CreateWritableCopyAsync(IPipelineFile source, string name, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        var target = GeneratePipelineFile(source.OriginalRelativePath, name, source.FileExtension);
        var targetPath = await target.GetLocalPathAsync(cancellationToken).ConfigureAwait(false);

        try
        {
            using var sourceStream = await source.OpenReadAsync(cancellationToken).ConfigureAwait(false);
            using var targetStream = target.OpenWriteFileStream();
            await sourceStream.CopyToAsync(targetStream, cancellationToken).ConfigureAwait(false);
        }
        catch
        {
            // A write that failed leaves no file: the caller never receives the target, so an incomplete
            // copy would only sit there until the pipeline directory is removed.
            TryDeleteIncompleteFile(targetPath);
            throw;
        }

        return target;
    }

    private static void TryDeleteIncompleteFile(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }

    /// <summary>
    /// Normalizes a relative path to forward-slash form without leading or trailing separators.
    /// Backslashes are tolerated (treated as separators); empty segments are collapsed.
    /// Rooted or absolute paths and <c>..</c> segments are rejected here so the canonical form
    /// stored on <see cref="IPipelineFile.OriginalRelativePath"/> is always safe.
    /// </summary>
    private static string NormalizeRelativePath(string relativePath)
    {
        if (string.IsNullOrEmpty(relativePath))
            return string.Empty;

        if (Path.IsPathRooted(relativePath))
            throw new ArgumentException($"Relative path <{relativePath}> must not be rooted or absolute.", nameof(relativePath));

        var segments = relativePath
            .Replace('\\', '/')
            .Split('/', StringSplitOptions.RemoveEmptyEntries);

        if (segments.Any(s => s == ".." || s == "."))
            throw new ArgumentException($"Relative path <{relativePath}> must not contain '.' or '..' segments.", nameof(relativePath));

        return string.Join('/', segments);
    }
}
