// <auto-generated />
using System;
using GeoCop.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoCop.Api.Migrations
{
    [DbContext(typeof(DeliveryContext))]
    partial class DeliveryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoCop.Api.Models.Delivery", b =>
                {
                    b.Property<string>("FileHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeclaringUserIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatId")
                        .HasColumnType("text");

                    b.HasKey("FileHash");

                    b.HasIndex("DeclaringUserIdentifier");

                    b.HasIndex("OperatId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("GeoCop.Api.Models.Operat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string[]>("FileTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Geometry>("SpatialExtent")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.ToTable("Operate");
                });

            modelBuilder.Entity("GeoCop.Api.Models.Organisation", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OperatId")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.HasIndex("OperatId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("GeoCop.Api.Models.User", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.HasKey("Identifier");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrganisationUser", b =>
                {
                    b.Property<string>("OrganisationsName")
                        .HasColumnType("text");

                    b.Property<string>("UsersIdentifier")
                        .HasColumnType("text");

                    b.HasKey("OrganisationsName", "UsersIdentifier");

                    b.HasIndex("UsersIdentifier");

                    b.ToTable("OrganisationUser");
                });

            modelBuilder.Entity("GeoCop.Api.Models.Delivery", b =>
                {
                    b.HasOne("GeoCop.Api.Models.User", "DeclaringUser")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeclaringUserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoCop.Api.Models.Operat", "Operat")
                        .WithMany("Deliveries")
                        .HasForeignKey("OperatId");

                    b.Navigation("DeclaringUser");

                    b.Navigation("Operat");
                });

            modelBuilder.Entity("GeoCop.Api.Models.Organisation", b =>
                {
                    b.HasOne("GeoCop.Api.Models.Operat", null)
                        .WithMany("Organisations")
                        .HasForeignKey("OperatId");
                });

            modelBuilder.Entity("OrganisationUser", b =>
                {
                    b.HasOne("GeoCop.Api.Models.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoCop.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoCop.Api.Models.Operat", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Organisations");
                });

            modelBuilder.Entity("GeoCop.Api.Models.User", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
