using Geopilot.PipelineCore.Pipeline;
using Microsoft.VisualBasic.FileIO;

namespace Geopilot.Api.Pipeline;

/// <inheritdoc />
public class PipelineFileManager : IPipelineFileManager
{
    private readonly string basePath;

    /// <summary>
    /// Create a PipelineFileManager with the specified base path for storing temporary files. The base path is used as the root directory for all temporary files generated by the pipeline.
    /// </summary>
    /// <param name="basePath">The base path for storing temporary files.</param>
    /// <param name="stepDirectory">The directory for the specific pipeline step.</param>
    public PipelineFileManager(string basePath, string stepDirectory)
    {
        if (!string.IsNullOrEmpty(stepDirectory))
            this.basePath = Path.Combine(basePath, stepDirectory);
        else
            this.basePath = basePath;

        if (!Path.Exists(this.basePath))
            Directory.CreateDirectory(this.basePath);
    }

    /// <inheritdoc />
    public IPipelineTransferFile GenerateTransferFile(string originalFileName, string fileExtension)
    {
        var filePath = Path.Combine(this.basePath, $"{originalFileName}_{Guid.NewGuid().ToString()}.{fileExtension}");
        return new PipelineTransferFile(filePath, originalFileName + "." + fileExtension);
    }
}
