namespace Geopilot.Api.Pipeline;

/// <inheritdoc />
public class PipelineFileManager : IPipelineFileManager
{
    private readonly string basePath;

    /// <summary>
    /// Create a PipelineFileManager with the specified base path for storing temporary files. The base path is used as the root directory for all temporary files generated by the pipeline.
    /// </summary>
    /// <param name="basePath"></param>
    public PipelineFileManager(string basePath)
    {
        this.basePath = basePath;
    }

    /// <inheritdoc />
    public string GenerateProcessorDirectory(Type processorType)
    {
        var processorDirectory = Path.Combine(this.basePath, processorType?.Name != null ? processorType.Name : "Unknown");
        Directory.CreateDirectory(processorDirectory);
        return processorDirectory;
    }

    /// <inheritdoc />
    public string GenerateTempFileName(string fileType, string fileExtension)
    {
        return $"{fileType}_{Guid.NewGuid().ToString()}.{fileExtension}";
    }
}
