name: 'Setup Dev Certificates'
description: 'Creates and trusts development certificates'

inputs:
  export-path:
    description: 'Path to export the certificate to'
    required: true
    default: './certs/geopilot.pem'
  trusted-cert-path:
    description: 'Path to the trusted certificate location on Ubuntu'
    required: true
    default: '/usr/local/share/ca-certificates/geopilot.crt'

runs:
  using: 'composite'
  steps:
      - name: Create dev-certs
        shell: bash
        run: |
          mkdir -p $(dirname ${{ inputs.export-path }})
          dotnet dev-certs https --export-path ${{ inputs.export-path }} --no-password --format PEM
          chmod 664 ${{ inputs.export-path }}

      - name: Trust dev-certs
        shell: bash
        run: |
          sudo apt-get install -y ca-certificates
          sudo cp ${{ inputs.export-path }} ${{ inputs.trusted-cert-path }}
          sudo update-ca-certificates
