name: CI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0"

      - name: Authenticate to GitHub Packages
        run: dotnet nuget update source github-geowerkstatt --username "$USERNAME" --password "%GITHUB_TOKEN%" --store-password-in-clear-text
        env:
          USERNAME: ${{ github.actor }}

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Install dependencies
        run: dotnet restore Geopilot.slnx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dotnet
        run: dotnet build Geopilot.slnx -c Release --no-restore /warnaserror

      - name: Run frontend ci install
        working-directory: ./src/Geopilot.Frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./src/Geopilot.Frontend
        run: npm run build --if-present

      - name: Check frontend types
        working-directory: ./src/Geopilot.Frontend
        run: npm run ts

      - name: Lint frontend
        working-directory: ./src/Geopilot.Frontend
        run: npm run lint

      - name: Knip frontend
        working-directory: ./src/Geopilot.Frontend
        run: npm run knip

      - name: Check migration history
        working-directory: ./src/Geopilot.Api
        run: dotnet tool run dotnet-ef migrations has-pending-model-changes

      - name: Setup dev-certs
        uses: ./.github/actions/setup-dev-certs

      - name: Start test environment
        run: docker compose up -d --wait --wait-timeout 120 db azurite clamav ilitools-wrapper

      - name: Test
        run: dotnet test Geopilot.slnx -c Release --no-build --verbosity normal

