name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start db and api's
        run: docker compose up --wait

      - name: Wait for keycloak
        run: |
          end=$((SECONDS+300))
          while [ $SECONDS -lt $end ]; do
            if curl --output /dev/null --silent --head --fail http://localhost:4011/realms/geopilot/.well-known/openid-configuration; then
              echo "Keycloak is available."
              exit 0
            fi
            echo "Waiting for Keycloak to be available..."
            sleep 5
          done
          echo "Timeout reached. Keycloak is still not available."
          exit 1

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }} --ci-build-id ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}
          wait-on: "http://localhost:5173"
          wait-on-timeout: 120
          working-directory: ./src/Geopilot.Frontend
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
